# Generated by Django 4.2.2 on 2023-11-09 14:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(default='admin', max_length=10)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('party', models.CharField(max_length=20)),
                ('sign', models.ImageField(upload_to='sign')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electionId', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='electionImage')),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.administrator')),
                ('candidates', models.ManyToManyField(related_name='eligible_candidates', to='voting.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterId', models.CharField(max_length=10)),
                ('voterName', models.CharField(max_length=20)),
                ('voterImage', models.ImageField(upload_to='voterImage')),
                ('voterEmail', models.EmailField(max_length=254)),
                ('voterPassword', models.CharField(max_length=200)),
                ('role', models.CharField(default='voter', max_length=10)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VoterOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 20, 14, 37, 463528))),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.voters')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.candidates')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(related_name='eligible_voters', to='voting.voters'),
        ),
        migrations.CreateModel(
            name='AdminOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(default=datetime.datetime(2023, 11, 9, 20, 14, 37, 463528))),
                ('administrator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.administrator')),
            ],
        ),
    ]
