# Generated by Django 4.2.2 on 2023-11-09 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 20, 37, 7, 883286)),
        ),
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 20, 38, 7, 889287)),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 20, 38, 7, 888285)),
        ),
    ]
