# Generated by Django 4.2.2 on 2023-11-09 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voters_createdat_alter_adminotp_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 21, 9, 46, 702970)),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 21, 9, 46, 701971)),
        ),
        migrations.AlterField(
            model_name='voters',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
