# Generated by Django 4.2.2 on 2023-11-10 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_alter_adminotp_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 12, 17, 728923)),
        ),
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 13, 17, 734922)),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 13, 17, 733921)),
        ),
    ]
