# Generated by Django 4.2.2 on 2023-11-10 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_administrator_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 13, 53, 145104)),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 15, 13, 53, 144057)),
        ),
    ]
