# Generated by Django 4.2.2 on 2023-11-11 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_alter_administrator_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 14, 18, 54, 695114)),
        ),
        migrations.AlterField(
            model_name='election',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='eligible_voters', to='voting.voters'),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 14, 18, 54, 695114)),
        ),
    ]
