# Generated by Django 4.2.2 on 2023-11-17 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_adminotp_otp_expires_at_alter_election_voters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='votedVoter',
            field=models.ManyToManyField(blank=True, related_name='voted_voters', to='voting.voters'),
        ),
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 11, 42, 994795)),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 15, 11, 42, 994795)),
        ),
    ]
