# Generated by Django 4.2.2 on 2023-11-23 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_adminotp_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='name',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 15, 36, 9, 309465)),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 15, 36, 9, 309465)),
        ),
    ]
