# Generated by Django 4.2.2 on 2023-11-23 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_administrator_name_alter_adminotp_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='image',
            field=models.ImageField(blank=True, upload_to='admin_profile'),
        ),
        migrations.AlterField(
            model_name='adminotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 15, 39, 33, 846569)),
        ),
        migrations.AlterField(
            model_name='voterotp',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 15, 39, 33, 846569)),
        ),
    ]
